sudo: false
language: go
go:
  - 1.6
  - tip
script:
  # Run go generate on all packages and check for changed files
  - go generate ./... && git status && git add --all . && [ ! -n "`git diff --staged HEAD`" ]
  # Test the schema package first so the database init fails the correct test
  - go test -v ./db/internal/schema -db 'dbname=travis_ci_test user=postgres sslmode=disable'
  # Test all packages in parallel
  - go test -v ./... -db 'dbname=travis_ci_test user=postgres sslmode=disable'
services:
  - postgresql
addons:
  # TODO: change this and plperl below to 9.5 when Travis CI supports it
  postgresql: 9.4
  apt:
    packages:
      # nodejs needed for go generate (lessc, etc.)
      - nodejs
      - postgresql-plperl-9.4
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/11ed5656d9814f0bed7a
    on_success: change
    on_failure: always
    on_start: never
